
### REST CLIENT EXTENSION TEST
GET https://jsonplaceholder.typicode.com/posts/1

### HEALTH CHECK
GET http://localhost:3000/api/utilities/health
X-App-Origin: dev
Accept-Language: en
###
GET https://www.festivaldesarts.merville31.fr/api/utilities/health
X-App-Origin: prod
###

### DATABASE SYNCING
GET http://localhost:3000/api/utilities/sync/fda_prod
###
GET http://localhost:3000/api/utilities/sync/fda_test
###

### USER
POST http://localhost:3000/api/register
content-type: application/json
X-App-Origin: dev
Accept-Language: en

{  
  "email":"henri.talfumier@wanadoo.fr",
  "idRole":1,
  "pwd":"644601"
}
###
POST https://www.festivaldesarts.merville31.fr/api/register
content-type: application/json
X-App-Origin: dev

{  
  "email":"henri.talfumier@wanadoo.fr",
  "idRole":1,
  "pwd":"644601"
}
###
