name: Deploy API to OVH

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 12496
          script: |
            rsync -avz --delete --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='node_modules' -e "ssh -p 12496" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/fda.fr/api
            cd /var/www/fda.fr/api
            npm run build
            /home/deploy/.npm-global/bin/pm2 restart api || /home/deploy/.npm-global/bin/pm2 start src/index.js --name api
